# Generated by Django 3.1.2 on 2020-10-21 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookies', '0002_auto_20201021_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='avg_sale',
            field=models.DecimalField(decimal_places=2, help_text='Enter the average number of cookies per sale', max_digits=5),
        ),
        migrations.AlterField(
            model_name='location',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Location Manager'),
        ),
        migrations.AlterField(
            model_name='location',
            name='max_customers',
            field=models.DecimalField(decimal_places=2, help_text='Enter minimum number of customers', max_digits=5),
        ),
        migrations.AlterField(
            model_name='location',
            name='min_customers',
            field=models.DecimalField(decimal_places=2, help_text='Enter minimum number of customers', max_digits=5),
        ),
    ]
