# Generated by Django 3.1.2 on 2020-10-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0003_auto_20201021_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='max_customers',
            field=models.IntegerField(help_text='Enter maximum number of customers'),
        ),
        migrations.AlterField(
            model_name='location',
            name='min_customers',
            field=models.IntegerField(help_text='Enter minimum number of customers'),
        ),
    ]
