# Generated by Django 3.1.2 on 2020-10-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0004_auto_20201021_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='image',
            field=models.ImageField(default='cookies/default.png', upload_to='cookies'),
        ),
    ]
