# Generated by Django 3.1.2 on 2020-10-21 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0005_cookie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='rating',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
